# Generated by Django 3.1.7 on 2021-04-04 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogpost', '0002_blogmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogmodel',
            old_name='categry',
            new_name='category',
        ),
    ]
